# Generated by Django 4.2.7 on 2026-04-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='banner_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='button_link',
            field=models.CharField(blank=True, default='', help_text='e.g., /products or /products/5', max_length=200),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='button_text_en',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='button_text_ur',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='banners/videos/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
