# Generated by Django 4.2.7 on 2026-04-26 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_herobanner_banner_type_herobanner_button_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='customer_photo',
            field=models.ImageField(blank=True, help_text='Photo of the customer (separate from video thumbnail)', null=True, upload_to='testimonials/photos/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Optional: link this feedback to a specific product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='api.product'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='show_on_about',
            field=models.BooleanField(default=True, help_text='Display on the about page'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='show_on_home',
            field=models.BooleanField(default=True, help_text='Display on the homepage'),
        ),
    ]
